dtype_mg = {
    "EAN": str,
    "DESCRIÇÃO" : str,
    "NCM_antigo" : str,
    "NCM_Valido" : str,
    "EX" : str,
    "% do IVA" : float,
    "ALIQUOTA_ICMS": float,
    "REDUCAO_ICMS": float,
    "CST_ICMS": str,
    "ALIQUOTA_PIS": float,
    "CST_PIS": str,
    "ALIQUOTA_COFINS": float,
    "CST_COFINS": str,
    "NATUREZA RECEITA": str,

}

dtype_controller = {
    "PRODUTO_ATIVO": str,
    "EAN": str,
    "PR_NOME": str,
    "EI_CST": str,
    "EI_ALQ": float,
    "EI_RBC": float,
    "MVA_PAUTA": float,
    "MVA": float,
    "SNC_CST": str,
    "SNC_ALQ": float,
    "SNC_RBC": float,
    "NCM": str,
    "NCM_EX": str,
    "PIS_CST_E": str,
    "PIS_ALQ_E": float,
    "COFINS_CST_E": str,
    "COFINS_ALQ_E": float,
    "PIS_CST_S": str,
    "PIS_ALQ_S": float,
    "COFINS_CST_S": str,
    "COFINS_ALQ_S": float,
    "COD_NATUREZA_CREDITO": str,
    "COD_NATUREZA_RECEITA": str,
    "IPI_VALOR": str,
    "UF_FCP": str,
    "ALQ_FCP": float,
    "ALQ_FCPST": float,
    "CEST_E": str,
    "EI_CBENEF": str,
    "CEST_S": str,
    "SNC_CBENEF": str,
}

CAMPOS_OBRIGATORIOS_MG = [
    "EAN",
    "NCM_VALIDADO",
    "EX",
    "% do IVA",
    "CST_ICMS",
    "ALIQUOTA_ICMS",
    "REDUCAO_ICMS",
    "CST_PIS",
    "ALIQUOTA_PIS",
    "CST_COFINS",
    "ALIQUOTA_COFINS",
    # "CEST",
    "CBENEF",
    "NATUREZA RECEITA"
]

CAMPOS_OBRIGATORIOS_CONTROLLER = [
    "PRODUTO_ATIVO",
    "EAN",
    "PR_NOME",
    "EI_CST",
    "EI_ALQ",
    "EI_RBC",
    "MVA_PAUTA",
    "MVA",
    "SNC_CST",
    "SNC_ALQ",
    "SNC_RBC",
    "NCM",
    "NCM_EX",
    "PIS_CST_E",
    "PIS_ALQ_E",
    "COFINS_CST_E",
    "COFINS_ALQ_E",
    "PIS_CST_S",
    "PIS_ALQ_S",
    "COFINS_CST_S",
    "COFINS_ALQ_S",
    "COD_NATUREZA_CREDITO",
    "COD_NATUREZA_RECEITA",
    "IPI_VALOR",
    "UF_FCP",
    "ALQ_FCP",
    "ALQ_FCPST",
    "CEST_E",
    "EI_CBENEF",
    "CEST_S",
    "SNC_CBENEF",
]